# Generated by Django 4.2.9 on 2024-01-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
